# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: portray-prettyprinter
version: 0.2.0
category: Text
synopsis: A portray backend using the prettyprinter package.
description: |
  This provides a
  <https://hackage.haskell.org/package/prettyprinter prettyprinter> backend for
  <https://hackage.haskell.org/package/portray portray> along with derivable
  'Pretty' instances for types with 'Portray' instances.

  This started out as a fork of
  <https://hackage.haskell.org/package/portray-pretty portray-pretty>, and is
  still very similar.  However, @prettyprinter@ gives more flexibility to
  documents at the cost of requiring more behavior to be specified explicitly.
  As such, some formats are nicer with the @prettyprinter@ backend,
  configurable syntax highlighting is supported, and unicode escaping is
  configurable.  However, this backend is less mature and hasn't been used as
  much in practice, so there are likely more formatting bugs than in
  @portray-pretty@.  Please do file bugs on the GitHub issue tracker if you
  find anything that seems obviously wrong!

  Try using 'pp' as the print function in GHCi:
  @:set -interactive-print=Data.Portray.Prettyprinter.pp@!
license: Apache-2.0
author: Andrew Pritchard <awpr@google.com>
copyright: 2021 Google LLC
maintainer: Andrew Pritchard <awpr@google.com>
github: google/hs-portray/portray-prettyprinter

# Note: this causes CHANGELOG.md to be included in Hackage distributions.
extra-source-files:
  CHANGELOG.md

dependencies:
  - base >= 4.12 && < 4.16
  - portray >= 0.2 && < 0.3
  - portray-diff >= 0.1 && < 0.2
  - prettyprinter >= 1.2 && < 1.8
  - prettyprinter-ansi-terminal >= 1.1.1 && < 1.2
  - text >= 0.1 && < 1.3

library:
  source-dirs: src
  exposed-modules:
    - Data.Portray.Prettyprinter

tests:
  PortrayPrettyprinter-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - portray
      - portray-prettyprinter
      - test-framework
      - test-framework-hunit
      - test-framework-quickcheck2
      - HUnit
      - QuickCheck
